# Generated by Django 2.1.1 on 2019-08-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='downvote',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='downvote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Downvote',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
