# Generated by Django 2.1.1 on 2019-08-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190831_1842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='downvote',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='downvote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Downvote',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
